server:
  port: 10086
spring:
  application:
    name: leyou-registry
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:10086/eureka/